meta_product_name: "Live music is all about passion"
meta_title: "CLAPEE"
meta_description: "Live music is all about passion"
meta_keywords: "clapee, avis concert, critique concert, concert paris, concert paris 2019, concert olympia, concert zénith, concert, festival, rap, rock, musique, electro, chanson"
meta_image: "bannerclapee.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@clapeemusic"
